builders:
  schema_builder:
    import: "package:built_graphql/builders.dart"
    builder_factories: ["schemaBuilder"]
    build_extensions: { ".graphql": [".graphql.dart"] }
    auto_apply: none
    build_to: source
  executable_builder:
    import: "package:built_graphql/builders.dart"
    builder_factories: ["executableBuilder"]
    build_extensions: { ".graphql": [".graphql.dart"] }
    auto_apply: none
    build_to: source

targets:
  $default:
    builders:
      built_graphql|schema_builder:
        enabled: true
      built_graphql|executable_builder:
        enabled: true
        options:
          schema: built_graphql|lib/schema.graphql
