builders:
  builder:
    import: "package:built_graphql/builder.dart"
    builder_factories: ["builtGraphQLBuilder"]
    build_extensions: { ".graphql": [".graphql.dart"] }
    auto_apply: none
    build_to: source
