targets:
  $default:
    sources:
      - lib/**

builders:
  schema_builder:
    import: "package:built_graphql/builder.dart"
    builder_factories: ["schemaBuilder"]
    build_extensions: { ".graphql": [".graphql.dart"] }
    auto_apply: none
    build_to: source

# targets:
#   $default:
#     builders:
#       gql_build|schema_builder:
#         enabled: true
