name: built_graphql
description: A starting point for Dart libraries or applications.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  gql: ^0.12.2
  built_collection: ^4.3.2
  built_value: ^7.0.9
  built_value_generator: ^7.0.9
  recase: ^3.0.0
  build: ^1.2.2
  dart_style: ^1.3.3

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
  build_runner: ^1.7.4
