name: major_graphql_generator
description: Generator component of major_graphql
version: 0.0.1
# homepage: https://www.example.com

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  recase: ^3.0.0
  build: ^1.2.2
  dart_style: ^1.3.3
  get_it: 4.0.0

  # We automatically apply these builders
  built_value_generator: #^7.0.9
    path: /Users/mjr/code/libraries/built_value.dart/built_value_generator
  gql_code_gen: ^0.1.5

  major_graphql:
    path: ../major_graphql

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
  build_runner: ^1.7.4
  build_test:
