name: major_graphql_example
version: 1.0.0+1
description: A major_graphql example
environment: 
  sdk: '>=2.7.0 <3.0.0'
dependencies: 
  built_collection: ^4.3.2
  built_value: ^7.0.9
  dart_style: ^1.3.3
  graphql_flutter: ^3.0.0
  major_graphql: ^0.0.1
  flutter: 
    sdk: flutter
  # https://github.com/flutter/flutter/issues/36126#issuecomment-596215587
  graphql_starwars_test_server: ^0.1.0
dev_dependencies: 
  test: ^1.6.0
  build_runner: ^1.7.4
  build_test: any
  major_graphql_generator:
    path: ../major_graphql_generator
  flutter_test: 
    sdk: flutter
flutter: 
  assets: 
    - lib/graphql/operations/
  uses-material-design: true

dependency_overrides:
  graphql_server:
    git:
      url: git@github.com:micimize/angel.git
      path: packages/graphql/graphql_server
  graphql_parser:
    git:
      url: git@github.com:micimize/angel.git
      path: packages/graphql/graphql_parser
