name: built_graphql
description: A starting point for Dart libraries or applications.
version: 0.0.1
# homepage: https://www.example.com

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  gql: ^0.12.2
  built_collection: ^4.3.2
  built_value: ^7.0.9

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
