name: major_graphql_flutter
description: graphql_flutter bindings for major_graphql
version: 0.0.2
homepage: https://github.com/micimize/major/tree/master/major_graphql_flutter

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  graphql: ^3.0.1
  graphql_flutter: ^3.0.1
  gql: ^0.12.2
  major_graphql: ^0.0.2
  #path: ../major_graphql

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.6.0
  pedantic: ^1.8.0

