name: major_graphql_flutter
version: 0.0.3
homepage: https://github.com/micimize/major/tree/master/major_graphql_flutter
description: graphql_flutter bindings for major_graphql
environment: 
  sdk: '>=2.7.0 <3.0.0'
dependencies: 
  graphql: ^4.0.0-beta
  graphql_flutter: ^4.0.0-beta
  gql: ^0.12.2
  flutter: 
    sdk: flutter
  major_graphql: 
    path: ../major_graphql
dev_dependencies: 
  test: ^1.6.0
  pedantic: ^1.8.0
  flutter_test: 
    sdk: flutter
