name: built_graphql_flutter
description: graphql_flutter bindings for built_graphql
version: 0.0.1
author: micimize
homepage:

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  graphql_flutter: ^3.0.0
  built_graphql: ^0.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.6.0
  pedantic: ^1.8.0

flutter:
