# TODO It might make more sense to have two different flows for the backend,
# 
on:
  push:
    paths:
      - 'todo_app/backend/@app/*'
    branches:
      - master

jobs:
  deploy-backend:
    name: Deploy Backend
    runs-on: ubuntu-latest

    env:
      NODE_ENV: 'production'
      DATABASE_HOST: 'localhost'
      DATABASE_PORT: '5432'
      DATABASE_NAME: 'todo_app'
      ENABLE_GRAPHIQL: 'true'
      DATABASE_VISITOR: 'todo_app_visitor'

      DATABASE_SUPERUSER: 'postgres'
      DATABASE_SUPERUSER_PASSWORD: ${{ secrets.DATABASE_SUPERUSER_PASSWORD }}

      DATABASE_OWNER: 'todo_app'
      DATABASE_OWNER_PASSWORD: ${{ secrets.DATABASE_OWNER_PASSWORD }}

      DATABASE_AUTHENTICATOR: 'todo_app_authenticator'
      DATABASE_AUTHENTICATOR_PASSWORD: ${{ secrets.DATABASE_AUTHENTICATOR_PASSWORD }}

      PROJECT_NAME: ${{ secrets.GCP_PROJECT_ID }}

    steps:
    - uses: actions/checkout@v2

    - name: Saturate App Engine Config & GCP Credentials
      uses: micimize/publish-gae-action@master
      with:
        gae_config_path: 'todo_app/backend/@app/server/app.yml'
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_email: ${{ secrets.GCP_SERVICE_ACCOUNT_EMAIL }}
        service_account_key: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
        # An optional variables parameter can be used
        gae_variables: ${{ secrets.GAE_VARIABLES }}

    - name: Activate Service Account
      run: |
        # This client-secret.json is reconstructed from GCP_SERVICE_ACCOUNT_KEY.
        # The service account needs the following roles:
        # * App Engine Deployer
        # * App Engine Service Admin
        # * Cloud Build Service Account
        # * Cloud SQL Client
        # * Storage Object Creator
        # * Storage Object Viewer 
        #
        # You also need:
        # * a Cloud SQL instance created, secured, and setup (todo_app/act/cloud_sql_setup.sh),
        # * a GAE created & Cloud Build API enabled
        gcloud auth activate-service-account \
          ${{ secrets.GCP_SERVICE_ACCOUNT_EMAIL }} \
          --key-file=client-secret.json
        gcloud config set project ${{ secrets.GCP_PROJECT_ID }}


    - name: Run Database Migrations
      working-directory: 'todo_app/backend/@app/db/'
      run: |
        # we use the cloud_sql_proxy so we can auth with the service account
        wget https://dl.google.com/cloudsql/cloud_sql_proxy.linux.amd64 -O cloud_sql_proxy
        chmod +x cloud_sql_proxy
        # We background the proxy, which (I'm pretty sure) gets auto-garbage collected
        # TODO this only works without a race condition because yarn is slowish
        ./cloud_sql_proxy -instances=${{ secrets.DATABASE_INSTANCE  }}=tcp:5432 &
        yarn && yarn migrate


    - name: Publish Server to Google App Engine
      working-directory: 'todo_app/backend/@app/server/'
      run: |
        yarn && yarn build
        gcloud -q app deploy app.yml --promote

